--
-- PostgreSQL database dump
--

-- Dumped from database version 16.9 (Debian 16.9-1.pgdg120+1)
-- Dumped by pg_dump version 16.9 (Debian 16.9-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: images; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.images (
    id bigint NOT NULL,
    data oid,
    name character varying(255),
    type character varying(255),
    maladies_id bigint NOT NULL
);


ALTER TABLE public.images OWNER TO postgres;

--
-- Name: images_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.images ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.images_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: maladies; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.maladies (
    id bigint NOT NULL,
    nom character varying(100) NOT NULL,
    type character varying(50)
);


ALTER TABLE public.maladies OWNER TO postgres;

--
-- Name: maladies_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.maladies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.maladies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: maladies_symptomes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.maladies_symptomes (
    maladies_id bigint NOT NULL,
    symptomes character varying(255)
);


ALTER TABLE public.maladies_symptomes OWNER TO postgres;

--
-- Name: maladies_traitements; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.maladies_traitements (
    maladies_id bigint NOT NULL,
    traitements character varying(255)
);


ALTER TABLE public.maladies_traitements OWNER TO postgres;

--
-- Name: patient_maladie; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.patient_maladie (
    patient_id bigint NOT NULL,
    maladie_id bigint NOT NULL
);


ALTER TABLE public.patient_maladie OWNER TO postgres;

--
-- Name: patients; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.patients (
    id bigint NOT NULL,
    email character varying(255),
    nom character varying(255),
    num_urgence integer NOT NULL,
    prenom character varying(255),
    telephone integer,
    groupesanguin character varying(2),
    stade smallint,
    CONSTRAINT patients_stade_check CHECK (((stade >= 0) AND (stade <= 4)))
);


ALTER TABLE public.patients OWNER TO postgres;

--
-- Name: patients_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.patients ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.patients_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: patients_symptomesmanifester; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.patients_symptomesmanifester (
    patients_id bigint NOT NULL,
    symptomesmanifester character varying(255)
);


ALTER TABLE public.patients_symptomesmanifester OWNER TO postgres;

--
-- Name: patients_traitementsuivie; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.patients_traitementsuivie (
    patients_id bigint NOT NULL,
    traitementsuivie character varying(255)
);


ALTER TABLE public.patients_traitementsuivie OWNER TO postgres;

--
-- Data for Name: images; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.images (id, data, name, type, maladies_id) FROM stdin;
\.


--
-- Data for Name: maladies; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.maladies (id, nom, type) FROM stdin;
1	Covid-19	Maladie virale
\.


--
-- Data for Name: maladies_symptomes; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.maladies_symptomes (maladies_id, symptomes) FROM stdin;
\.


--
-- Data for Name: maladies_traitements; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.maladies_traitements (maladies_id, traitements) FROM stdin;
\.


--
-- Data for Name: patient_maladie; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.patient_maladie (patient_id, maladie_id) FROM stdin;
\.


--
-- Data for Name: patients; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.patients (id, email, nom, num_urgence, prenom, telephone, groupesanguin, stade) FROM stdin;
1	jean.kouam@example.com	Kouam	0	Jean	677889900	AB	3
\.


--
-- Data for Name: patients_symptomesmanifester; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.patients_symptomesmanifester (patients_id, symptomesmanifester) FROM stdin;
1	Difficulté respiratoire
1	Douleurs musculaires
1	Forte fièvre
\.


--
-- Data for Name: patients_traitementsuivie; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.patients_traitementsuivie (patients_id, traitementsuivie) FROM stdin;
1	Antibiotiques
1	Hydratation intraveineuse
1	Ventilation assistée
\.


--
-- Name: images_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.images_id_seq', 1, false);


--
-- Name: maladies_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.maladies_id_seq', 1, true);


--
-- Name: patients_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.patients_id_seq', 1, true);


--
-- Name: images images_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.images
    ADD CONSTRAINT images_pkey PRIMARY KEY (id);


--
-- Name: maladies maladies_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.maladies
    ADD CONSTRAINT maladies_pkey PRIMARY KEY (id);


--
-- Name: patient_maladie patient_maladie_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.patient_maladie
    ADD CONSTRAINT patient_maladie_pkey PRIMARY KEY (patient_id, maladie_id);


--
-- Name: patients patients_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.patients
    ADD CONSTRAINT patients_pkey PRIMARY KEY (id);


--
-- Name: patients ukaitcny1v8j351nsyaj8vd1jo9; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.patients
    ADD CONSTRAINT ukaitcny1v8j351nsyaj8vd1jo9 UNIQUE (telephone);


--
-- Name: images ukfmo789oy544k7jxnnx3q8uetw; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.images
    ADD CONSTRAINT ukfmo789oy544k7jxnnx3q8uetw UNIQUE (name);


--
-- Name: patients uko7ki1qdfhdp4h6ordqea6yh0q; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.patients
    ADD CONSTRAINT uko7ki1qdfhdp4h6ordqea6yh0q UNIQUE (email);


--
-- Name: maladies_traitements fk2q4x3vi5ow7p42g1yrocj6hgi; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.maladies_traitements
    ADD CONSTRAINT fk2q4x3vi5ow7p42g1yrocj6hgi FOREIGN KEY (maladies_id) REFERENCES public.maladies(id);


--
-- Name: patient_maladie fk5dotyrhi6q25kkhboxt72wihc; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.patient_maladie
    ADD CONSTRAINT fk5dotyrhi6q25kkhboxt72wihc FOREIGN KEY (maladie_id) REFERENCES public.maladies(id);


--
-- Name: patients_symptomesmanifester fk6npdxtectapddfr8k0wif9io; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.patients_symptomesmanifester
    ADD CONSTRAINT fk6npdxtectapddfr8k0wif9io FOREIGN KEY (patients_id) REFERENCES public.patients(id);


--
-- Name: maladies_symptomes fk763c1i0x787arli1dlinhgc0i; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.maladies_symptomes
    ADD CONSTRAINT fk763c1i0x787arli1dlinhgc0i FOREIGN KEY (maladies_id) REFERENCES public.maladies(id);


--
-- Name: patient_maladie fk9gercf18q7f6pr3tnlxymkw63; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.patient_maladie
    ADD CONSTRAINT fk9gercf18q7f6pr3tnlxymkw63 FOREIGN KEY (patient_id) REFERENCES public.patients(id);


--
-- Name: patients_traitementsuivie fkirj11wdif3ta784u8p8k8nohe; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.patients_traitementsuivie
    ADD CONSTRAINT fkirj11wdif3ta784u8p8k8nohe FOREIGN KEY (patients_id) REFERENCES public.patients(id);


--
-- Name: images fktbfdd43jqqhh9935lykc7qr5n; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.images
    ADD CONSTRAINT fktbfdd43jqqhh9935lykc7qr5n FOREIGN KEY (maladies_id) REFERENCES public.maladies(id);


--
-- PostgreSQL database dump complete
--

